Milestone 2
pbkabali/React-Calculator pull request #2
Opened 2021-02-02 16:33 UTC by pbkabali

## What this PR does:
- Add component structure of the app
- Implement the Display component
- Implement the ButtonPanel component
- Implement the button component

[Live link](https://shielded-everglades-20664.herokuapp.com/)

2021-02-02 17:30 UTC, whiz25 requested changes
## Changes Required :pray: 
Nice work @pbkabali you did well in this PR. The codebase is well structured. All components are rightly placed in the `components` directory.
Make the following changes so we can merge this PR.
- [ ] add description to your PR. Tell us what the PR is about, the features that the PR covers.
- [ ] the result of the calculation should be a string. check my comment for suggestion


### Martin Afani

2021-02-02 17:30 UTC, whiz25 commented on src/components/Display.js
> +  result: 0,
- The value of `result` should be a string
```javascript
result: '0'
```

2021-02-02 17:43 UTC, pbkabali commented
Thanks a lot @whiz25 for the review. I have made improvements and made a resubmission.

2021-02-02 18:35 UTC, christianotieno approved these changes
## Milestone Approved 🍾 
Hello @pbkabali 👋 
The changes are now reflecting 👏 
I wish you all the best in your next tasks 🥇 

### Happy coding 💻 
#### Christian Otieno (CR)

2021-02-03 00:06 UTC, pbkabali commented
Thank you very much @christianotieno

2021-02-03 00:07 UTC, merged